### ISSUE TITLE
compound model

### ISSUE THREAD

**Issue by dmlyons2** [Chemical-Curation/chemcurator_django#2]
@kdionisio commented on [Thu Jan 16 2020](https://github.com/Chemical-Curation/chemcurator_ws/issues/1)

As a product owner
I would like to store a compound
So that I can use it in my application

This is an abstract class

Compound consists of:
- DTXCID002000000 (auto increment from 2,000,000 up) (required field)
- Definitive structure string - Text Field (required field)

Acceptance Criteria:
- A test to show when a compound is created it has the appropriate ID and Definitive structure

**Comment by debboutr** [comment]
here's my thought of how the Compound models could go...

```
from django.db import models


class CommonInfo (models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey('User', on_delete=models.PROTECT)
    updated_by = models.ForeignKey('User', null=True, blank=True, 
                                        on_delete=models.PROTECT)

    class Meta:
        abstract = True

class Compound (CommonInfo):
    structure = models.CharField(max_length='???')

    @property
    def dtxcid (self):
        return f'DTXCID{self.pk + 2000000}'

class DefinedCompound (Compound):
    inchikey = models.CharField(max_length=30)

class IllDefinedCompound (Compound):
    pass

class QueryStructureType (models.Model):
    compound = models.ForeignKey('IllDefinedCompound', on_delete=models.PROTECT)
    name = models.CharField(max_length='???')
```

**Comment by mcovalt** [comment]
I propose a different approach that somewhat mimics the way `DateTimeField` works. As far as Python is concerned, the field is always a `datetime` object. SQL sees a specially formatted string. This is done via a custom field.

In the following approach, all we ever see and use is a "DTXCID00*****" string. The database uses integers. We need to find a way to start the increment at 2,000,000 so that posts of "DTXCID00X" where "X" < 2,000,000 are allowed.

This approach centralizes the logic going from integer to DTXCID similarly to your property field, but allows us to never have to make the conversion from int to DTXCID and vice versa elsewhere in our code (e.g. querying, serializing, etc).

The `StructureAliasField` allows us to simply alias `definitive_structure_string` based on the subclass so that we can query and operate on  e.g. `DefinedCompound.definitive_structure_string` and `DefinedCompound.molfile_v3000` equally. This may come in handy when making generic functions expecting a `Model.definitive_structure_string` and avoiding excessive branching when dealing with polymorphic models.

**Fields**

```python
from django.db import models

from compound import validators

class DTXCIDField(models.AutoField):
    """Represents the DTXCID as an integer sequence in SQL, but a DTXCID
    string in Python.
    """
    default_validators = [validators.SomeValidation, validators.SomeOtherValidation]

    def parse_int_to_dtxcid(self, db_int):
        """Go from integer to DTXCID string."""
        return f"DTXCID00{db_int}"

    def parse_dtxcid_to_int(self, dtxcid):
        """Go from DTXCID string to integer."""
        # More logic here as we go along.
        return int(dtxcid[8:]) if dtxcid else None


    ###############
    # Boilerplate #
    ###############
    def from_db_value(self, *args):
        """Called when getting value from database."""
        db_int = super().from_db_value(*args)
        if db_int:
            return self.parse_int_to_dtxcid(db_int)
        return None

    def to_python(self, value):
        """Called when deserializing."""
        if isinstance(value, str) and value[:6] == "DTXCID":
            return value
        db_int = super().to_python(value)
        if db_int:
            return self.parse_int_to_dtxcid(db_int)
        return None

    def get_db_prep_value(self, value, *args, **kwargs):
        """Go from Python string to SQL integer."""
        if isinstance(value, str) and value[:6] == "DTXCID":
            db_int = self.parse_dtxcid_to_int()
            return super().get_db_prep_value(db_int, *args, **kwargs)
        return super().get_db_prep_value(value, *args, **kwargs)

class StructureAliasField(models.Field):
    """Aliases to definitive_structure_string, but can be called something else.

    yanked from here: https://djangosnippets.org/snippets/10440/
    """
    def contribute_to_class(self, cls, name, private_only=False):
        super().contribute_to_class(cls, name, private_only=True)
        setattr(cls, name, self)

    def __get__(self, instance, instance_type=None):
        return getattr(instance, "definitive_structure_string")
```

**Models**

```python
from django.db import models

from compound.fields import DTXCIDField, StructureAliasField

class CommonInfo (models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey('User', on_delete=models.PROTECT)
    updated_by = models.ForeignKey('User', null=True, blank=True,
                                        on_delete=models.PROTECT)

    class Meta:
        abstract = True

class Compound(CommonInfo):
    id = DTXCIDField(primary_key=True)
    definitive_structure_string = models.TextField()

class DefinedCompound(Compound):
    molfile_v3000 = StructureAliasField()
    inchikey = models.CharField(max_length=30)

class IllDefinedCompound(Compound):
    mrvfile = StructureAliasField()
    ...
```

**Comment by mwfrost** [comment]
Tests should include both the minting of new DTXCIDs with serial numbers >= 2 million and the insertion of existing ones where the serial number is lower than 2 million.

**Comment by debboutr** [comment]
@cmgrulke are we to assume that the `DTXCID` field will never be entered by the user? and just auto-populated when the compound is created?

**Comment by cmgrulke** [comment]
This not accurate.  Since I will be managing the import of the legacy data, I plan on having the ability to PUT resources to specified dtxcids (issue 35).  This will also help me if I spin up separate deployments of this API in research environments and want to load them in and merge records (issues 36 and 39)
