### ISSUE TITLE
substance compound 1:1

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#235]
As a *cheminformatian*
I want *substances and compounds to have a 1:1 relationship*
So that *a single structural depiction cannot be erroneously linked to multiple substances and a substance cannot be depicted erroneously with different structures.*

Acceptance Criteria:
the relationship between substances and compounds is 0/1 : 0/1

Test:

**Comment by michael-barbour** [comment]
This ticket can be closed.  I made this change in #231 due to this being a probable blocker.

The code is here on the substance model _chemreg/substance/models.py_ line 121 `associated_compound = models.OneToOneField`
and on the substance migration _chemreg/substance/migrations/0007_orion_sprint.py_ line 47

It looks like our api

**Comment by debboutr** [comment]
@michael-barbour this makes sense, I guess if `replaced_by` is not null, it will have to point to that compound.

Thanks for getting this done!

**Comment by jtumkur** [comment]
Did not required code change as part #54
