### ISSUE TITLE
V3000 molfile validation

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#28]
**As a** researcher
**I want** the API to ensure my V3000 molfile is properly formatted
**So that** when molfiles stored by the system are returned to me, I can be confident they are correct

**Request Example**
`POST https://api.chemreg.epa.gov/defined-compounds/`

**Acceptance Criteria:**
When I post a v3000 molfile to the API, It verifies that the molfile conforms to proper V3000 format prior to returning success
If the file is not v3000, the input is invalid (415 or 400?) (Message: "MolFile format is invalid.  Molfile v3000 format expected.").

**Test:**

**Comment by cmgrulke** [comment]
Validating a molfile is correct is difficult.  I typically punt on that and assume that if the file is interpretable by a chemical toolkit, it is a valid structural format.  Since, our storage format is specifically v3000, which I would recommend checking for that by verifying 4th line ends with "V3000".  Documentation of the current definition for molfile formats are attached.

[ctfile.pdf](https://github.com/Chemical-Curation/chemcurator_django/files/4167106/ctfile.pdf)

**Comment by cmgrulke** [comment]
Attached are three molfiles...
[molfiles.zip](https://github.com/Chemical-Curation/chemcurator_django/files/4167285/molfiles.zip)

**Comment by debboutr** [comment]
Looking into this it seems we might need to isolate error handling with `indigo` to find errors that may occur in the `loadMolecule` method. Right now the `get_inchikey` function uses `loadMolecule` before it can check to find an `inchikey`. In this ticket we want to add a check for `V3000` molfile which will be checking for this string at the end of the counts line as documented  on page 9, [here](https://www.daylight.com/meetings/mug05/Kappler/ctfile.pdf). The existence of this string would not necessarily be a reason for `loadMolecule` to fail, but like the inchikey validation, all that the user would get back is...
* `"InChIKey not computable for provided structure."` OR
* `"Molfile is not in V3000 format."`

Would we want to pass back to the user the specific errors that `loadMolecule` might throw? Or are we happy with having one of the 2 messages above in order to tell the user that there is a problem with the molfile? Here are a few exceptions from `indigo`:
* `IndigoException: scanner: BufferScanner::read() error`
* `IndigoException: scanner: readInt(): error parsing`
* `IndigoException: molfile loader: error reading CTAB block header`

Would it make sense to pull validation out to give these messages to the user?

**Comment by mwfrost** [comment]
When it comes time to demo this ticket, paste the following V2000 molfile into the text box on the browsable API's Defined Compound page:

```
  -INDIGO-04152015462D

 13 13  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  2  4  1  0  0  0  0
  4  5  1  0  0  0  0
  5  6  2  0  0  0  0
  6  7  1  0  0  0  0
  7  8  2  0  0  0  0
  8  9  1  0  0  0  0
  9 10  2  0  0  0  0
 10  5  1  0  0  0  0
  6 11  1  0  0  0  0
 11 12  1  0  0  0  0
 11 13  2  0  0  0  0
M  END
```

The response should look like this:
```
HTTP 400 Bad Request
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/vnd.api+json
Vary: Accept

{
    "errors": [
        {
            "detail": "Structure is not in V3000 format.",
            "status": "400",
            "source": {
                "pointer": "/data/attributes/molfileV3000"
            },
            "code": "invalid"
        },
        {
            "detail": "InChIKey not computable for provided structure.",
            "status": "400",
            "source": {
                "pointer": "/data/attributes/molfileV3000"
            },
            "code": "invalid"
        }
    ]
}
```
