### ISSUE TITLE
InChIKey Uniqueness override

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_django#32]
**As a** admin
**I want** to be able to override "inchikey uniqueness check" that restricts researchers
**So that** I can in the rare cases where the standard inchikey canonicalization is wrong store what I manually deem after review of the potential conflict to be different chemical concepts  

**Request Example**
?????????

**Acceptance Criteria:**
When a InChIKey conflict occurs that causes a POST to defined compounds to be rejected, I need as an admin a way to override that.  It should not be overridden by default just because I am an admin...
The new "conflicted" defined compounds should appear the same on read as any other compound.

**Test:**

**Comment by debboutr** [comment]
@cmgrulke there are a few ways to go about adding permissions to do this. The simplest way would probably be to apply these permissions to Users that have the `is_superuser` attribute to `True`. This can be flipped on any user, but would also give them permissions to the admin site and the ability to make modifications to any other User. Are you the only one that will likely be using these permissions? or will you give others this ability? If it's just you, I think this will work fine, otherwise, we may want to discuss how we'll create and apply this permission. thanks

**Comment by cmgrulke** [comment]
I expect that it will for now be me.  In the future I could see one or two others being added, but I am fine with using the "is_superuser" set to true for now.  I think the way that works might change if we move to something other than django admin site user management, but lets cross that bridge later.
