### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by dmlyons2** [Chemical-Curation/chemcurator_django#75]
As a researcher/developer
I want documentation for the api - similiar to api.factotum.epa.gov with examples in python / R on how to use the api
So that it is easy to find and understand what the api does 

Acceptance Criteria:

Test:

**Comment by mcovalt** [comment]
In factotum, we used [drf-yasg](https://github.com/axnsan12/drf-yasg) to setup the tooling to automatically generate the OpenAPI Specification Document and [redoc](https://github.com/Redocly/redoc) to view it. This proved to be fairly difficult. I fear that this difficulty will be substantially increased with the use of the JSON:API schema.

Since the work on factotum, the official Django REST Framework package [has _significantly_ increased their focus](https://github.com/encode/django-rest-framework/pulls?utf8=%E2%9C%93&q=label%3A%22Schema+Generation%22+) on automatic OpenAPI Specification Document generation. This will be significantly more robust than [drf-yasg](https://github.com/axnsan12/drf-yasg). The JSON:API package also has an [in-progress PR](https://github.com/django-json-api/django-rest-framework-json-api/pull/772) to work in tandem with the official DRF schema generation.

It might be worth considering manually writing the OpenAPI Specification Document yaml in the meantime rather than building complex tools to generate this documentation automatically. [There are tools](https://swagger.io/tools/swagger-editor/) to make this very simple.
